from __future__ import annotations


REFERENCE_TIENKUNG2_LITE_SNAPSHOT = {
    "asset_name": "tienkung2_lite",
    "source_hint": "TienKung-Lab/legged_lab/assets/tienkung2_lite",
    "urdf": {
        "links": {
            "pelvis": {
                "mass": 27.771712,
                "collision_count": 1,
                "collision_specs": (
                    {
                        "origin": {"xyz": "-0.02 0.0 -0.11", "rpy": "1.57 0 0"},
                        "geometry": {"tag": "cylinder", "attrib": {"length": "0.11", "radius": "0.085"}},
                    },
                ),
            },
            "hip_roll_l_link": {"mass": 0.672983, "collision_count": 0},
            "hip_pitch_l_link": {"mass": 3.951912, "collision_count": 0},
            "hip_yaw_l_link": {
                "mass": 6.670795,
                "collision_count": 1,
                "collision_specs": (
                    {
                        "origin": {"xyz": "0.0 0.0 -0.1", "rpy": "0 0 0"},
                        "geometry": {"tag": "cylinder", "attrib": {"length": "0.2", "radius": "0.03"}},
                    },
                ),
            },
            "knee_pitch_l_link": {
                "mass": 2.312685,
                "collision_count": 1,
                "collision_specs": (
                    {
                        "origin": {"xyz": "0.0 0.0 -0.15", "rpy": "0 0 0"},
                        "geometry": {"tag": "cylinder", "attrib": {"length": "0.3", "radius": "0.03"}},
                    },
                ),
            },
            "ankle_pitch_l_link": {"mass": 0.111609, "collision_count": 0},
            "ankle_roll_l_link": {
                "mass": 1.017381,
                "collision_count": 2,
                "collision_specs": (
                    {
                        "name": "toe1_left",
                        "origin": {"xyz": "0.035 0.025 -0.042", "rpy": "0 1.5708 0"},
                        "geometry": {"tag": "cylinder", "attrib": {"length": "0.23", "radius": "0.015"}},
                    },
                    {
                        "name": "toe2_left",
                        "origin": {"xyz": "0.035 -0.025 -0.042", "rpy": "0 1.5708 0"},
                        "geometry": {"tag": "cylinder", "attrib": {"length": "0.23", "radius": "0.015"}},
                    },
                ),
            },
            "hip_roll_r_link": {"mass": 0.672983, "collision_count": 0},
            "hip_pitch_r_link": {"mass": 3.951912, "collision_count": 0},
            "hip_yaw_r_link": {
                "mass": 6.670795,
                "collision_count": 1,
                "collision_specs": (
                    {
                        "origin": {"xyz": "0.0 0.0 -0.1", "rpy": "0 0 0"},
                        "geometry": {"tag": "cylinder", "attrib": {"length": "0.2", "radius": "0.03"}},
                    },
                ),
            },
            "knee_pitch_r_link": {
                "mass": 2.312685,
                "collision_count": 1,
                "collision_specs": (
                    {
                        "origin": {"xyz": "0.0 0.0 -0.15", "rpy": "0 0 0"},
                        "geometry": {"tag": "cylinder", "attrib": {"length": "0.3", "radius": "0.03"}},
                    },
                ),
            },
            "ankle_pitch_r_link": {"mass": 0.111609, "collision_count": 0},
            "ankle_roll_r_link": {
                "mass": 1.017381,
                "collision_count": 2,
                "collision_specs": (
                    {
                        "name": "toe1_right",
                        "origin": {"xyz": "0.035 0.025 -0.042", "rpy": "0 1.5708 0"},
                        "geometry": {"tag": "cylinder", "attrib": {"length": "0.23", "radius": "0.015"}},
                    },
                    {
                        "name": "toe2_right",
                        "origin": {"xyz": "0.035 -0.025 -0.042", "rpy": "0 1.5708 0"},
                        "geometry": {"tag": "cylinder", "attrib": {"length": "0.23", "radius": "0.015"}},
                    },
                ),
            },
            "shoulder_pitch_l_link": {"mass": 0.469057, "collision_count": 0},
            "shoulder_roll_l_link": {
                "mass": 0.298029,
                "collision_count": 1,
                "collision_specs": (
                    {
                        "origin": {"xyz": "0 0 0", "rpy": "0 0 0"},
                        "geometry": {"tag": "sphere", "attrib": {"radius": "0.035"}},
                    },
                ),
            },
            "shoulder_yaw_l_link": {"mass": 0.93608, "collision_count": 0},
            "elbow_pitch_l_link": {
                "mass": 0.553799,
                "collision_count": 1,
                "collision_specs": (
                    {
                        "origin": {"xyz": "0 -0.0 0", "rpy": "0 0 0"},
                        "geometry": {"tag": "sphere", "attrib": {"radius": "0.035"}},
                    },
                ),
            },
            "shoulder_pitch_r_link": {"mass": 0.469057, "collision_count": 0},
            "shoulder_roll_r_link": {
                "mass": 0.298029,
                "collision_count": 1,
                "collision_specs": (
                    {
                        "origin": {"xyz": "0 0 0", "rpy": "0 0 0"},
                        "geometry": {"tag": "sphere", "attrib": {"radius": "0.035"}},
                    },
                ),
            },
            "shoulder_yaw_r_link": {"mass": 0.93608, "collision_count": 0},
            "elbow_pitch_r_link": {
                "mass": 0.553799,
                "collision_count": 1,
                "collision_specs": (
                    {
                        "origin": {"xyz": "0 0.0 0", "rpy": "0 0 0"},
                        "geometry": {"tag": "sphere", "attrib": {"radius": "0.035"}},
                    },
                ),
            },
        },
        "joints": {
            "hip_roll_l_joint": {
                "type": "revolute",
                "axis": "1 0 0",
                "lower": "-0.79",
                "upper": "0.79",
                "effort": "180",
                "velocity": "15.6",
                "parent": "pelvis",
                "child": "hip_roll_l_link",
            },
            "hip_pitch_l_joint": {
                "type": "revolute",
                "axis": "0 1 0",
                "lower": "-2.79",
                "upper": "2.09",
                "effort": "300",
                "velocity": "15.6",
                "parent": "hip_roll_l_link",
                "child": "hip_pitch_l_link",
            },
            "hip_yaw_l_joint": {
                "type": "revolute",
                "axis": "0 0 1",
                "lower": "-1.04",
                "upper": "1.04",
                "effort": "180",
                "velocity": "15.6",
                "parent": "hip_pitch_l_link",
                "child": "hip_yaw_l_link",
            },
            "knee_pitch_l_joint": {
                "type": "revolute",
                "axis": "0 1 0",
                "lower": "0.0",
                "upper": "2.39",
                "effort": "300",
                "velocity": "15.6",
                "parent": "hip_yaw_l_link",
                "child": "knee_pitch_l_link",
            },
            "ankle_pitch_l_joint": {
                "type": "revolute",
                "axis": "0 1 0",
                "lower": "-1.22",
                "upper": "0.5236",
                "effort": "60",
                "velocity": "12.8",
                "parent": "knee_pitch_l_link",
                "child": "ankle_pitch_l_link",
            },
            "ankle_roll_l_joint": {
                "type": "revolute",
                "axis": "1 0 0",
                "lower": "-0.4363",
                "upper": "0.4363",
                "effort": "30",
                "velocity": "7.8",
                "parent": "ankle_pitch_l_link",
                "child": "ankle_roll_l_link",
            },
            "hip_roll_r_joint": {
                "type": "revolute",
                "axis": "1 0 0",
                "lower": "-0.79",
                "upper": "0.79",
                "effort": "180",
                "velocity": "15.6",
                "parent": "pelvis",
                "child": "hip_roll_r_link",
            },
            "hip_pitch_r_joint": {
                "type": "revolute",
                "axis": "0 1 0",
                "lower": "-2.79",
                "upper": "2.09",
                "effort": "300",
                "velocity": "15.6",
                "parent": "hip_roll_r_link",
                "child": "hip_pitch_r_link",
            },
            "hip_yaw_r_joint": {
                "type": "revolute",
                "axis": "0 0 1",
                "lower": "-1.04",
                "upper": "1.04",
                "effort": "180",
                "velocity": "15.6",
                "parent": "hip_pitch_r_link",
                "child": "hip_yaw_r_link",
            },
            "knee_pitch_r_joint": {
                "type": "revolute",
                "axis": "0 1 0",
                "lower": "0.0",
                "upper": "2.39",
                "effort": "300",
                "velocity": "15.6",
                "parent": "hip_yaw_r_link",
                "child": "knee_pitch_r_link",
            },
            "ankle_pitch_r_joint": {
                "type": "revolute",
                "axis": "0 1 0",
                "lower": "-1.22",
                "upper": "0.5236",
                "effort": "60",
                "velocity": "12.8",
                "parent": "knee_pitch_r_link",
                "child": "ankle_pitch_r_link",
            },
            "ankle_roll_r_joint": {
                "type": "revolute",
                "axis": "1 0 0",
                "lower": "-0.4363",
                "upper": "0.4363",
                "effort": "30",
                "velocity": "7.8",
                "parent": "ankle_pitch_r_link",
                "child": "ankle_roll_r_link",
            },
            "shoulder_pitch_l_joint": {
                "type": "revolute",
                "axis": "0 1 0",
                "lower": "-2.96",
                "upper": "2.96",
                "effort": "52.5",
                "velocity": "14.1",
                "parent": "pelvis",
                "child": "shoulder_pitch_l_link",
            },
            "shoulder_roll_l_joint": {
                "type": "revolute",
                "axis": "1 0 0",
                "lower": "-0.2618",
                "upper": "3.4",
                "effort": "52.5",
                "velocity": "14.1",
                "parent": "shoulder_pitch_l_link",
                "child": "shoulder_roll_l_link",
            },
            "shoulder_yaw_l_joint": {
                "type": "revolute",
                "axis": "0 0 1",
                "lower": "-2.96",
                "upper": "2.96",
                "effort": "52.5",
                "velocity": "14.1",
                "parent": "shoulder_roll_l_link",
                "child": "shoulder_yaw_l_link",
            },
            "elbow_pitch_l_joint": {
                "type": "revolute",
                "axis": "0 1 0",
                "lower": "-2.61",
                "upper": "0.261",
                "effort": "52.5",
                "velocity": "14.1",
                "parent": "shoulder_yaw_l_link",
                "child": "elbow_pitch_l_link",
            },
            "shoulder_pitch_r_joint": {
                "type": "revolute",
                "axis": "0 1 0",
                "lower": "-2.96",
                "upper": "2.96",
                "effort": "52.5",
                "velocity": "14.1",
                "parent": "pelvis",
                "child": "shoulder_pitch_r_link",
            },
            "shoulder_roll_r_joint": {
                "type": "revolute",
                "axis": "1 0 0",
                "lower": "-3.4",
                "upper": "0.2618",
                "effort": "52.5",
                "velocity": "14.1",
                "parent": "shoulder_pitch_r_link",
                "child": "shoulder_roll_r_link",
            },
            "shoulder_yaw_r_joint": {
                "type": "revolute",
                "axis": "0 0 1",
                "lower": "-2.96",
                "upper": "2.96",
                "effort": "52.5",
                "velocity": "14.1",
                "parent": "shoulder_roll_r_link",
                "child": "shoulder_yaw_r_link",
            },
            "elbow_pitch_r_joint": {
                "type": "revolute",
                "axis": "0 1 0",
                "lower": "-2.61",
                "upper": "0.261",
                "effort": "52.5",
                "velocity": "14.1",
                "parent": "shoulder_yaw_r_link",
                "child": "elbow_pitch_r_link",
            },
        },
        "link_count": 21,
        "joint_count": 20,
        "fixed_joint_count": 0,
        "revolute_joint_count": 20,
        "total_mass": 61.760372,
        "nonzero_collision_links": 11,
        "total_collision_elems": 13,
    },
    "usd_config": {
        "fix_base": "false",
        "merge_fixed_joints": "true",
        "self_collision": "false",
        "collision_from_visuals": "false",
    },
    "usd_markers": {
        "exists": True,
        "has_root_joint": False,
        "has_fixed_token": False,
    },
}
